/**
 * Built-in Themes — DevVerse Desktop
 *
 * Each theme is a complete CSS variable map.
 * The ThemeContext applies these variables to :root at runtime.
 */

import type { BuiltInTheme } from '@/types/theme.types';

export const BUILT_IN_THEMES: BuiltInTheme[] = [
  // ── DevVerse Dark (Default) ──────────────────────────────────────────────
  {
    id: 'devverse-dark',
    name: 'DevVerse Dark',
    description: 'The default dark theme — clean, professional, deep.',
    isDark: true,
    vars: {
      '--bg-app':           '#070709',
      '--bg-surface':       '#0e0f14',
      '--bg-elevated':      '#14161d',
      '--bg-hover':         '#1a1c26',
      '--text-primary':     '#f0f2f8',
      '--text-secondary':   '#8890a8',
      '--text-muted':       '#464e65',
      '--border-subtle':    'rgba(255,255,255,0.05)',
      '--border-medium':    'rgba(255,255,255,0.09)',
      '--border-bright':    'rgba(255,255,255,0.16)',
      '--titlebar-bg':      '#05050a',
      '--titlebar-text':    '#f0f2f8',
      '--titlebar-icon':    '#8890a8',
      '--sidebar-bg':       '#0b0c11',
      '--input-bg':         '#070709',
      '--scrollbar-thumb':  'rgba(255,255,255,0.09)',
    },
  },

  // ── DevVerse Light ───────────────────────────────────────────────────────
  {
    id: 'devverse-light',
    name: 'DevVerse Light',
    description: 'A bright, clean workspace — high readability.',
    isDark: false,
    vars: {
      '--bg-app':           '#f5f6fa',
      '--bg-surface':       '#ffffff',
      '--bg-elevated':      '#eff0f5',
      '--bg-hover':         '#e8eaf2',
      '--text-primary':     '#0f1221',
      '--text-secondary':   '#4b5275',
      '--text-muted':       '#9298b0',
      '--border-subtle':    'rgba(0,0,0,0.07)',
      '--border-medium':    'rgba(0,0,0,0.12)',
      '--border-bright':    'rgba(0,0,0,0.20)',
      '--titlebar-bg':      '#e8eaf2',
      '--titlebar-text':    '#0f1221',
      '--titlebar-icon':    '#4b5275',
      '--sidebar-bg':       '#eef0f7',
      '--input-bg':         '#f5f6fa',
      '--scrollbar-thumb':  'rgba(0,0,0,0.14)',
    },
  },

  // ── GitHub Dark ──────────────────────────────────────────────────────────
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    description: 'Familiar GitHub dark interface.',
    isDark: true,
    vars: {
      '--bg-app':           '#0d1117',
      '--bg-surface':       '#161b22',
      '--bg-elevated':      '#1c2128',
      '--bg-hover':         '#21262d',
      '--text-primary':     '#e6edf3',
      '--text-secondary':   '#8b949e',
      '--text-muted':       '#484f58',
      '--border-subtle':    'rgba(240,246,252,0.07)',
      '--border-medium':    'rgba(240,246,252,0.12)',
      '--border-bright':    'rgba(240,246,252,0.20)',
      '--titlebar-bg':      '#090d13',
      '--titlebar-text':    '#e6edf3',
      '--titlebar-icon':    '#8b949e',
      '--sidebar-bg':       '#111519',
      '--input-bg':         '#0d1117',
      '--scrollbar-thumb':  'rgba(240,246,252,0.12)',
    },
  },

  // ── GitHub Light ─────────────────────────────────────────────────────────
  {
    id: 'github-light',
    name: 'GitHub Light',
    description: 'Clean GitHub light interface.',
    isDark: false,
    vars: {
      '--bg-app':           '#f6f8fa',
      '--bg-surface':       '#ffffff',
      '--bg-elevated':      '#eaeef2',
      '--bg-hover':         '#e2e7ed',
      '--text-primary':     '#1f2328',
      '--text-secondary':   '#636c76',
      '--text-muted':       '#9198a1',
      '--border-subtle':    'rgba(31,35,40,0.07)',
      '--border-medium':    'rgba(31,35,40,0.13)',
      '--border-bright':    'rgba(31,35,40,0.22)',
      '--titlebar-bg':      '#ebebeb',
      '--titlebar-text':    '#1f2328',
      '--titlebar-icon':    '#636c76',
      '--sidebar-bg':       '#f0f2f4',
      '--input-bg':         '#f6f8fa',
      '--scrollbar-thumb':  'rgba(0,0,0,0.15)',
    },
  },

  // ── VS Code Dark ─────────────────────────────────────────────────────────
  {
    id: 'vscode-dark',
    name: 'VS Code Dark',
    description: 'The iconic VS Code dark theme.',
    isDark: true,
    vars: {
      '--bg-app':           '#1e1e1e',
      '--bg-surface':       '#252526',
      '--bg-elevated':      '#2d2d30',
      '--bg-hover':         '#37373d',
      '--text-primary':     '#d4d4d4',
      '--text-secondary':   '#9d9d9d',
      '--text-muted':       '#5a5a5a',
      '--border-subtle':    'rgba(255,255,255,0.06)',
      '--border-medium':    'rgba(255,255,255,0.11)',
      '--border-bright':    'rgba(255,255,255,0.18)',
      '--titlebar-bg':      '#3c3c3c',
      '--titlebar-text':    '#cccccc',
      '--titlebar-icon':    '#9d9d9d',
      '--sidebar-bg':       '#1e1e1e',
      '--input-bg':         '#1e1e1e',
      '--scrollbar-thumb':  'rgba(255,255,255,0.11)',
    },
  },

  // ── One Dark ─────────────────────────────────────────────────────────────
  {
    id: 'one-dark',
    name: 'One Dark',
    description: 'Atom\'s iconic One Dark theme.',
    isDark: true,
    vars: {
      '--bg-app':           '#21252b',
      '--bg-surface':       '#282c34',
      '--bg-elevated':      '#2c313c',
      '--bg-hover':         '#343a45',
      '--text-primary':     '#abb2bf',
      '--text-secondary':   '#636d83',
      '--text-muted':       '#4b5263',
      '--border-subtle':    'rgba(255,255,255,0.06)',
      '--border-medium':    'rgba(255,255,255,0.10)',
      '--border-bright':    'rgba(255,255,255,0.17)',
      '--titlebar-bg':      '#1a1e24',
      '--titlebar-text':    '#abb2bf',
      '--titlebar-icon':    '#636d83',
      '--sidebar-bg':       '#21252b',
      '--input-bg':         '#21252b',
      '--scrollbar-thumb':  'rgba(255,255,255,0.10)',
    },
  },

  // ── Dracula ──────────────────────────────────────────────────────────────
  {
    id: 'dracula',
    name: 'Dracula',
    description: 'The beloved Dracula theme — bold and vivid.',
    isDark: true,
    vars: {
      '--bg-app':           '#191a21',
      '--bg-surface':       '#282a36',
      '--bg-elevated':      '#323444',
      '--bg-hover':         '#3a3d50',
      '--text-primary':     '#f8f8f2',
      '--text-secondary':   '#a0a5be',
      '--text-muted':       '#6272a4',
      '--border-subtle':    'rgba(248,248,242,0.06)',
      '--border-medium':    'rgba(248,248,242,0.10)',
      '--border-bright':    'rgba(248,248,242,0.18)',
      '--titlebar-bg':      '#13141c',
      '--titlebar-text':    '#f8f8f2',
      '--titlebar-icon':    '#a0a5be',
      '--sidebar-bg':       '#1e1f29',
      '--input-bg':         '#191a21',
      '--scrollbar-thumb':  'rgba(98,114,164,0.4)',
    },
  },

  // ── Nord ─────────────────────────────────────────────────────────────────
  {
    id: 'nord',
    name: 'Nord',
    description: 'Arctic, north-bluish color palette.',
    isDark: true,
    vars: {
      '--bg-app':           '#242933',
      '--bg-surface':       '#2e3440',
      '--bg-elevated':      '#3b4252',
      '--bg-hover':         '#434c5e',
      '--text-primary':     '#eceff4',
      '--text-secondary':   '#d8dee9',
      '--text-muted':       '#7b88a1',
      '--border-subtle':    'rgba(216,222,233,0.06)',
      '--border-medium':    'rgba(216,222,233,0.11)',
      '--border-bright':    'rgba(216,222,233,0.20)',
      '--titlebar-bg':      '#1e2430',
      '--titlebar-text':    '#eceff4',
      '--titlebar-icon':    '#d8dee9',
      '--sidebar-bg':       '#262c38',
      '--input-bg':         '#242933',
      '--scrollbar-thumb':  'rgba(216,222,233,0.14)',
    },
  },

  // ── Catppuccin Mocha ─────────────────────────────────────────────────────
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    description: 'Soothing pastel theme — Mocha variant.',
    isDark: true,
    vars: {
      '--bg-app':           '#181825',
      '--bg-surface':       '#1e1e2e',
      '--bg-elevated':      '#252538',
      '--bg-hover':         '#302d41',
      '--text-primary':     '#cdd6f4',
      '--text-secondary':   '#bac2de',
      '--text-muted':       '#6c7086',
      '--border-subtle':    'rgba(205,214,244,0.06)',
      '--border-medium':    'rgba(205,214,244,0.10)',
      '--border-bright':    'rgba(205,214,244,0.18)',
      '--titlebar-bg':      '#11111b',
      '--titlebar-text':    '#cdd6f4',
      '--titlebar-icon':    '#bac2de',
      '--sidebar-bg':       '#1b1b2e',
      '--input-bg':         '#181825',
      '--scrollbar-thumb':  'rgba(205,214,244,0.12)',
    },
  },

  // ── Tokyo Night ──────────────────────────────────────────────────────────
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    description: 'Inspired by the neon lights of Tokyo at night.',
    isDark: true,
    vars: {
      '--bg-app':           '#13141f',
      '--bg-surface':       '#1a1b26',
      '--bg-elevated':      '#21222e',
      '--bg-hover':         '#292b3d',
      '--text-primary':     '#c0caf5',
      '--text-secondary':   '#9099c0',
      '--text-muted':       '#565f89',
      '--border-subtle':    'rgba(192,202,245,0.06)',
      '--border-medium':    'rgba(192,202,245,0.10)',
      '--border-bright':    'rgba(192,202,245,0.18)',
      '--titlebar-bg':      '#0e0f18',
      '--titlebar-text':    '#c0caf5',
      '--titlebar-icon':    '#9099c0',
      '--sidebar-bg':       '#161723',
      '--input-bg':         '#13141f',
      '--scrollbar-thumb':  'rgba(192,202,245,0.12)',
    },
  },

  // ── Gruvbox Dark ─────────────────────────────────────────────────────────
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    description: 'Retro groove — warm tones, easy on the eyes.',
    isDark: true,
    vars: {
      '--bg-app':           '#1d2021',
      '--bg-surface':       '#282828',
      '--bg-elevated':      '#32302f',
      '--bg-hover':         '#3c3836',
      '--text-primary':     '#ebdbb2',
      '--text-secondary':   '#a89984',
      '--text-muted':       '#665c54',
      '--border-subtle':    'rgba(235,219,178,0.07)',
      '--border-medium':    'rgba(235,219,178,0.13)',
      '--border-bright':    'rgba(235,219,178,0.22)',
      '--titlebar-bg':      '#141617',
      '--titlebar-text':    '#ebdbb2',
      '--titlebar-icon':    '#a89984',
      '--sidebar-bg':       '#1d2021',
      '--input-bg':         '#1d2021',
      '--scrollbar-thumb':  'rgba(235,219,178,0.13)',
    },
  },

  // ── Solarized Dark ───────────────────────────────────────────────────────
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    description: 'Ethan Schoonover\'s classic Solarized dark palette.',
    isDark: true,
    vars: {
      '--bg-app':           '#002b36',
      '--bg-surface':       '#073642',
      '--bg-elevated':      '#0d4352',
      '--bg-hover':         '#12505f',
      '--text-primary':     '#fdf6e3',
      '--text-secondary':   '#93a1a1',
      '--text-muted':       '#586e75',
      '--border-subtle':    'rgba(253,246,227,0.07)',
      '--border-medium':    'rgba(253,246,227,0.12)',
      '--border-bright':    'rgba(253,246,227,0.20)',
      '--titlebar-bg':      '#001f29',
      '--titlebar-text':    '#fdf6e3',
      '--titlebar-icon':    '#93a1a1',
      '--sidebar-bg':       '#002b36',
      '--input-bg':         '#002b36',
      '--scrollbar-thumb':  'rgba(253,246,227,0.12)',
    },
  },
];

export const getThemeById = (id: string): BuiltInTheme => {
  return BUILT_IN_THEMES.find((t) => t.id === id) ?? BUILT_IN_THEMES[0];
};
